type: TartanAirv2
name: viode_export_example
args:
  root: /data/viode_rosbag_export/tartanair_v2_like/P000
  compressed: true
  imu_freq: 100
  gtFlow: false
  gtDepth: false
  gtPose: true
  imu_sim:
    acc_bias: [0.02, -0.01, 0.05]
    acc_init_bias_noise: [0.01, 0.01, 0.01]
    acc_bias_instability: [0.000147, 0.000147, 0.000147]
    acc_random_walk: [1.96e-07, 1.96e-07, 1.96e-07]
    gyro_bias: [0.005, -0.002, 0.005]
    gyro_init_bias_noise: [0.01, 0.01, 0.01]
    gyro_bias_instability: [5.8e-06, 5.8e-06, 5.8e-06]
    gyro_random_walk: [3.8e-07, 3.8e-07, 3.8e-07]
