Model:
  name: "DynGRU_VKitti2_HPC"
  stage: "vkitti2"
  suffix: "dyngru_vk2_hpc"
  gamma: 0.85
  max_flow: 400
  batch_size: 6
  sum_freq: 100
  val_freq: 10000
  image_size: [480, 640]
  image_scale: 1
  add_noise: True
  cov_mask: False

  critical_params: []
  transformer: "latentcostformer"
  restore_ckpt: "Model/MACVO_FrontendCov.pth"
  training_mode: "dyn"

  latentcostformer:
    pe: "linear"
    dropout: 0.0
    encoder_latent_dim: 256
    query_latent_dim: 64
    cost_latent_input_dim: 64
    cost_latent_token_num: 8
    cost_latent_dim: 128
    arc_type: "transformer"
    cost_heads_num: 1
    pretrain: True

  aug:
    color_jitter:
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue: 0.1
    eraser:
      scale: [0.02, 0.2]
      ratio: [0.3, 3.3]

  scheduler:
    type: OneCycleLR
    args:
      max_lr: 5e-4
      total_steps: 0
      pct_start: 0.05
      cycle_momentum: False
      anneal_strategy: "cos"

  num_epochs: 20
  save_freq: 2000
  val_freq: 2000
  log_freq: 100

Train:
  data: Config/Sequence/Training_Dataset/VKitti2_HPC_Supervised.yaml
