Model:
  name: "DynGRU_VIODE_HPC"
  stage: "tartanair"
  suffix: "dyngru_hpc"
  gamma: 0.85
  max_flow: 400
  batch_size: 6
  sum_freq: 100
  val_freq: 10000
  image_size: [480, 640]
  image_scale: 1
  add_noise: True
  cov_mask: False

  critical_params: []
  transformer: "latentcostformer"
  restore_ckpt: "Model/MACVO_FrontendCov.pth"
  training_mode: "dyn"
  dyn_loss_type: "fixed"       # "mahalanobis" | "scalar" | "fixed"
  dyn_sigma: 2.0              # fixed σ [px] for "fixed" mode

  latentcostformer:
    pe: "linear"
    dropout: 0.0
    encoder_latent_dim: 256
    query_latent_dim: 64
    cost_latent_input_dim: 64
    cost_latent_token_num: 8
    cost_latent_dim: 128
    arc_type: "transformer"
    cost_heads_num: 1
    pretrain: True
    context_concat: False
    encoder_depth: 3
    feat_cross_attn: False
    patch_size: 8
    patch_embed: "single"
    no_pe: False
    gma: "GMA"
    kernel_size: 9
    rm_res: True
    vert_c_dim: 64
    cost_encoder_res: True
    cnet: "twins"
    fnet: "twins"
    no_sc: False
    only_global: False
    add_flow_token: True
    use_mlp: False
    vertical_conv: False
    decoder_depth: 12
    critical_params: ["cost_heads_num", "vert_c_dim", "cnet", "pretrain",
                      "add_flow_token", "encoder_depth", "gma", "cost_encoder_res"]

  ### TRAINER
  clip: 1.0
  num_steps: &num_steps 300000

  optimizer:
    type: "AdamW"
    args:
      lr: &lr 2.0e-4
      weight_decay: 1.0e-4
      eps: 1.0e-8

  scheduler:
    type: "OneCycleLR"
    args:
      total_steps: *num_steps
      pct_start: 0.05
      cycle_momentum: False
      max_lr: *lr
      anneal_strategy: "linear"

  folderlength: None
  autosave_freq: 5000
  num_workers: 8
  mixed_precision: True
  seed: 1234
  log_freq: 100
  datatype: fp32
  wandb: True
  visual_freq: 500

Train:
  data: !flatten_seq
    - !include ../Sequence/Training_Dataset/TartanAirV2_TrainEasy_DynGRU.yaml
    - !include ../Sequence/Training_Dataset/TartanAirV2_TrainHard_DynGRU.yaml

Evaluate:
  data: !flatten_seq
    - !include ../Sequence/Training_Dataset/TartanAirV2_Test_DynGRU.yaml
